from matplotlib.axes import Axes
from matplotlib.lines import Line2D
from matplotlib.figure import Figure
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Line3D
from matplotlib.quiver import Quiver
from matplotlib.text import Text
from matplotlib.legend import Legend
from matplotlib.ticker import ScalarFormatter